"use client";
import { useState } from "react";
interface InteractionCheckerProps { currentMedications: string[]; }
interface Result { drug1: string; drug2: string; severity: "mild" | "moderate" | "severe"; description: string; }
const sev: Record<string, { bg: string; text: string; label: string }> = { mild: { bg: "bg-green-100", text: "text-green-700", label: "Mild" }, moderate: { bg: "bg-amber-100", text: "text-amber-700", label: "Moderate" }, severe: { bg: "bg-red-100", text: "text-red-700", label: "Severe" } };
export default function InteractionChecker({ currentMedications }: InteractionCheckerProps) {
  const [drug, setDrug] = useState(""); const [checking, setChecking] = useState(false); const [results, setResults] = useState<Result[] | null>(null); const [none, setNone] = useState(false);
  const check = async () => { if (!drug.trim()) return; setChecking(true); setResults(null); setNone(false); await new Promise(r => setTimeout(r, 1200)); const res: Result[] = []; const d = drug.trim().toLowerCase(); currentMedications.forEach((m) => { const ml = m.toLowerCase(); if ((d.includes("warfarin") && ml.includes("aspirin")) || (d.includes("aspirin") && ml.includes("warfarin"))) res.push({ drug1: drug.trim(), drug2: m, severity: "severe", description: "Increased bleeding risk." }); }); if (!res.length) setNone(true); else setResults(res); setChecking(false); };
  return (<div className="rounded-lg border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-semibold text-foreground">Interaction Checker</h2><p className="mt-1 text-xs text-muted-foreground">Check drug interactions with current prescriptions.</p><div className="mt-4 flex gap-2"><input type="text" value={drug} onChange={(e) => setDrug(e.target.value)} onKeyDown={(e) => e.key === "Enter" && check()} placeholder="Enter medication..." className="flex-1 rounded-md border border-border bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" /><button onClick={check} disabled={checking || !drug.trim()} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{checking ? "Checking..." : "Check"}</button></div>{currentMedications.length > 0 && (<div className="mt-3"><p className="text-xs text-muted-foreground mb-1">Against {currentMedications.length} active meds:</p><div className="flex flex-wrap gap-1.5">{currentMedications.map((m) => (<span key={m} className="rounded-full bg-muted px-2.5 py-0.5 text-xs text-muted-foreground">{m}</span>))}</div></div>)}{none && (<div className="mt-4 rounded-md border border-green-200 bg-green-50 p-3"><p className="text-sm text-green-700">No known interactions found.</p></div>)}{results && (<div className="mt-4 space-y-3"><p className="text-sm font-medium text-destructive">{results.length} interaction{results.length !== 1 ? "s" : ""} found:</p>{results.map((r, i) => { const s = sev[r.severity] ?? sev.mild; return (<div key={i} className="rounded-md border border-border p-3"><div className="flex items-center justify-between"><p className="text-sm font-medium text-foreground">{r.drug1} + {r.drug2}</p><span className={`rounded-full px-2 py-0.5 text-xs font-medium ${s.bg} ${s.text}`}>{s.label}</span></div><p className="mt-1 text-xs text-muted-foreground">{r.description}</p></div>); })}</div>)}</div>);
}
