"use client";
import { useState, useRef } from "react";
import apiClient from "@/lib/api-client";
interface ReportUploaderProps { onUploadSuccess?: () => void; }
const TYPES = [{ value: "lab", label: "Lab Results" }, { value: "imaging", label: "Imaging" }, { value: "pathology", label: "Pathology" }, { value: "radiology", label: "Radiology" }, { value: "discharge", label: "Discharge Summary" }, { value: "consultation", label: "Consultation" }, { value: "other", label: "Other" }];
export default function ReportUploader({ onUploadSuccess }: ReportUploaderProps) {
  const [isOpen, setIsOpen] = useState(false); const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(""); const [reportType, setReportType] = useState("lab"); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => { const f = e.target.files?.[0]; if (!f) return; if (f.size > 10*1024*1024) { setError("File must be under 10MB"); return; } setError(null); setFile(f); };
  const handleUpload = async () => { if (!file || !title.trim()) { setError("Provide title and file"); return; } setUploading(true); setError(null); try { const u = JSON.parse(localStorage.getItem("user") || "{}"); const fd = new FormData(); fd.append("file", file); fd.append("title", title.trim()); fd.append("report_type", reportType); fd.append("patient_id", u.id ?? u.patient_id); await apiClient.post("/reports/upload", fd, { headers: { "Content-Type": "multipart/form-data" }, timeout: 30000 }); setSuccess(true); setFile(null); setTitle(""); onUploadSuccess?.(); setTimeout(() => { setSuccess(false); setIsOpen(false); }, 2000); } catch { setError("Upload failed."); } finally { setUploading(false); } };
  return (<div><button onClick={() => { setFile(null); setTitle(""); setError(null); setSuccess(false); setIsOpen(!isOpen); }} className="inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 transition-colors">{isOpen ? "Cancel" : "Upload Report"}</button>{isOpen && (<div className="mt-4 rounded-lg border border-border bg-card p-6 shadow-sm"><h3 className="text-sm font-semibold text-foreground">Upload New Report</h3><div className="mt-4 space-y-4"><div><label className="block text-sm font-medium text-foreground">Title</label><input type="text" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g., Blood Panel" className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm" /></div><div><label className="block text-sm font-medium text-foreground">Type</label><select value={reportType} onChange={(e) => setReportType(e.target.value)} className="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm">{TYPES.map((o) => (<option key={o.value} value={o.value}>{o.label}</option>))}</select></div><div><label className="block text-sm font-medium text-foreground">File</label><input ref={fileRef} type="file" accept=".pdf,.jpg,.jpeg,.png,.txt,.docx" onChange={handleFile} className="mt-1 block w-full text-sm" />{file && <p className="mt-1 text-xs">{file.name}</p>}</div>{error && <p className="text-sm text-destructive">{error}</p>}{success && <p className="text-sm text-green-600">Uploaded!</p>}<button onClick={handleUpload} disabled={uploading || !file || !title.trim()} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{uploading ? "Uploading..." : "Upload & Analyze"}</button></div></div>)}</div>);
}
