"use client";
import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import apiClient from "@/lib/api-client";
import { ArrowLeft, Mail, Phone, Shield, Calendar, Clock, UserCheck, UserX, Activity } from "lucide-react";
interface UserDetail { id: string; email: string; first_name: string; last_name: string; role: string; is_active: boolean; last_login_at: string | null; created_at: string; phone: string | null; }
interface AuditEntry { id: string; action: string; resource_type: string; created_at: string; }
const RS: Record<string, string> = { patient: "bg-blue-100 text-blue-800", doctor: "bg-green-100 text-green-800", nurse: "bg-purple-100 text-purple-800", admin: "bg-red-100 text-red-800" };
export default function UserDetailPage() {
  const params = useParams(); const router = useRouter(); const userId = params.id as string;
  const [user, setUser] = useState<UserDetail | null>(null); const [auditLogs, setAuditLogs] = useState<AuditEntry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { loadUser(); }, [userId]); // eslint-disable-line react-hooks/exhaustive-deps
  const loadUser = async () => { setLoading(true); setError(null); try { const r = await apiClient.get("/admin/users/" + userId); setUser(r.data.user ?? r.data); } catch { try { const [p, d] = await Promise.allSettled([apiClient.get("/patients/" + userId), apiClient.get("/doctors/" + userId)]); if (p.status === "fulfilled") setUser({ ...(p.value.data.patient ?? p.value.data), role: "patient" }); else if (d.status === "fulfilled") setUser({ ...(d.value.data.doctor ?? d.value.data), role: "doctor" }); else setError("User not found."); } catch { setError("Failed."); } } try { const a = await apiClient.get("/admin/audit-logs?user_id=" + userId); const l = a.data.logs ?? a.data.audit_logs ?? a.data ?? []; if (Array.isArray(l)) setAuditLogs(l.slice(0, 10)); } catch {} setLoading(false); };
  const toggleStatus = async () => { if (!user) return; try { await apiClient.patch("/admin/users/" + userId, { is_active: !user.is_active }); } catch {} setUser({ ...user, is_active: !user.is_active }); };
  if (loading) return (<div className="space-y-6"><button onClick={() => router.push("/admin/users")} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back</button><div className="flex items-center justify-center py-16"><div className="h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" /></div></div>);
  if (error || !user) return (<div className="space-y-6"><button onClick={() => router.push("/admin/users")} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back</button><div className="rounded-lg border border-destructive/30 bg-destructive/5 p-6 text-center"><p className="text-sm text-destructive">{error ?? "Not found."}</p></div></div>);
  return (<div className="space-y-6"><button onClick={() => router.push("/admin/users")} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to Users</button>
    <div className="rounded-lg border border-border bg-card p-6 shadow-sm"><div className="flex items-start justify-between"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary/10 text-xl font-bold text-primary">{(user.first_name ?? "U")[0]}{(user.last_name ?? "")[0]}</div><div><h1 className="text-2xl font-bold text-foreground">{user.first_name} {user.last_name}</h1><span className={"inline-flex rounded-full px-2.5 py-0.5 text-xs font-medium " + (RS[user.role] ?? "bg-gray-100 text-gray-700")}>{user.role}</span></div></div><button onClick={toggleStatus} className={"inline-flex items-center gap-2 rounded-md border px-3 py-1.5 text-sm font-medium " + (user.is_active !== false ? "border-red-200 text-red-700 hover:bg-red-50" : "border-green-200 text-green-700 hover:bg-green-50")}>{user.is_active !== false ? <><UserX className="h-4 w-4" />Deactivate</> : <><UserCheck className="h-4 w-4" />Activate</>}</button></div></div>
    <div className="grid gap-6 md:grid-cols-2"><div className="rounded-lg border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-semibold text-foreground">Contact</h2><div className="mt-4 space-y-3"><div className="flex items-center gap-3"><Mail className="h-4 w-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Email</p><p className="text-sm font-medium text-foreground">{user.email ?? "N/A"}</p></div></div><div className="flex items-center gap-3"><Phone className="h-4 w-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Phone</p><p className="text-sm font-medium text-foreground">{user.phone ?? "N/A"}</p></div></div></div></div><div className="rounded-lg border border-border bg-card p-6 shadow-sm"><h2 className="text-lg font-semibold text-foreground">Account</h2><div className="mt-4 space-y-3"><div className="flex items-center gap-3"><Shield className="h-4 w-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Role</p><p className="text-sm font-medium capitalize text-foreground">{user.role}</p></div></div><div className="flex items-center gap-3"><Calendar className="h-4 w-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Created</p><p className="text-sm text-foreground">{user.created_at ? new Date(user.created_at).toLocaleString() : "N/A"}</p></div></div><div className="flex items-center gap-3"><Clock className="h-4 w-4 text-muted-foreground" /><div><p className="text-xs text-muted-foreground">Last Login</p><p className="text-sm text-foreground">{user.last_login_at ? new Date(user.last_login_at).toLocaleString() : "Never"}</p></div></div></div></div></div>
    {auditLogs.length > 0 && (<div className="rounded-lg border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-4"><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-muted-foreground" /><h2 className="text-lg font-semibold text-foreground">Recent Activity</h2></div></div><div className="divide-y divide-border">{auditLogs.map((log) => (<div key={log.id} className="flex items-center justify-between px-6 py-3 text-sm"><span className="inline-flex rounded-full bg-muted px-2 py-0.5 text-xs font-medium text-foreground">{log.action}</span><span className="text-xs text-muted-foreground">{new Date(log.created_at).toLocaleString()}</span></div>))}</div></div>)}
  </div>);
}